### ISSUE TITLE
WARN RegistrationTask - Encountered error during registration. Will retry in 60 seconds.

### ISSUE THREAD

**Issue by SimonCheung1989** [Appdynamics/appdynamics-docker-images#5]
`➜  ~ docker run -d \
-e APPDYNAMICS_CONTROLLER_HOST_NAME=**.saas.appdynamics.com \
-e APPDYNAMICS_CONTROLLER_PORT=443 \
-e APPDYNAMICS_CONTROLLER_SSL_ENABLED=false \
-e APPDYNAMICS_AGENT_ACCOUNT_NAME=** \
-e APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY=** \
-e MACHINE_AGENT_PROPERTIES="-Dappdynamics.sim.enabled=true -Dappdynamics.docker.enabled=true" \
-v /:/hostroot:ro -v /var/run/docker.sock:/var/run/docker.sock \
store/appdynamics/machine:4.5`

Hi, When i run the command and use `docker exec` to enter into the container, then execute below command
`# cd /opt/appdynamics/logs`
`# ls`
`machine-agent.log`
`# tail -200f machine-agent.log`
`[main] 12 Nov 2018 03:41:53,996  INFO FlexibleX509TrustManager - Using default keystore for SSL certificate validation.`
`[system-thread-0] 12 Nov 2018 03:42:01,689  WARN RegistrationTask - Encountered error during registration. Will retry in 60 seconds.`
`[system-thread-0] 12 Nov 2018 03:42:59,942  WARN RegistrationTask - Encountered error during registration. Will retry in 60 seconds.`
`[system-thread-0] 12 Nov 2018 03:44:01,151  WARN RegistrationTask - Encountered error during registration. Will retry in 60 seconds.`
`[system-thread-0] 12 Nov 2018 03:44:59,846  WARN RegistrationTask - Encountered error during registration. Will retry in 60 seconds.`
`[system-thread-0] 12 Nov 2018 03:46:00,408  WARN RegistrationTask - Encountered error during registration. Will retry in 60 seconds.`

Seems the agent cannot connect to the appD controller successfully. Any idea? i can't find any data from my controller.

**Comment by SimonCheung1989** [comment]
after i changed `APPDYNAMICS_CONTROLLER_SSL_ENABLED=true`, seems could connect successfully, but got below error
`# tail -200f machine-agent.log
[main] 12 Nov 2018 03:50:32,052  INFO FlexibleX509TrustManager - Using default keystore for SSL certificate validation.`
`[system-thread-0] 12 Nov 2018 03:50:36,878  INFO SecondStageSystem - Starting main system with features Features(features=[dmm], reason=Features.Reason(message=Unsuccessful leasing a Server Monitoring license, code=License Lease Failed))`

Is that caused my appD account license? i am using the free account.

**Comment by SimonCheung1989** [comment]
Yup, Just confirmed in appDynamics controller, the issue caused by free account do not support the feature. Just leave the issues here for others to reference. Thanks!!

**Comment by ayushghosh** [comment]
Also, the env variable APPDYNAMICS_CONTROLLER_SSL_ENABLED=false should be true when using SSL port.
